import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { collectLatestTimeline, AUTHOR } from '../src/sources/fxembed.ts';
import { fetchSource } from '../src/source.ts';
import { planSync, applySync, sourceOnly } from '../src/sync.ts';
import { readJson, writeJson } from '../src/storage.ts';
import type { Extraction } from '../src/types.ts';
const now=Math.floor(Date.now()/1000);
const row=(id:string,seconds=now-60,text='A product announcement.')=>({type:'status',id,url:`https://x.com/thsottiaux/status/${id}`,text,raw_text:{text},author:{id:AUTHOR.id,screen_name:AUTHOR.handle},created_at:new Date(seconds*1000).toUTCString(),created_timestamp:seconds});
const page=(rows:unknown[])=>new Response(JSON.stringify({code:200,results:rows,cursor:{bottom:'never-follow'}}),{headers:{'Content-Type':'application/json'}});
const unknown:Extraction={event_type:'unknown',state:'unknown',audience:[],time_expression:'',evidence:'',time_zone:null};

test('latest-only requests one page, sorts and filters old pinned originals, without inventing text',async()=>{
 const urls:string[]=[];
 const b=await collectLatestTimeline(24,(async(u:RequestInfo|URL)=>{urls.push(String(u));return page([row('1',now-90000),row('2',now-120),row('3',now-60)]);}) as typeof fetch);
 assert.equal(urls.length,1);assert.ok(!urls[0].includes('cursor='));assert.ok(urls[0].includes('with_replies=1'));
 assert.deepEqual(b.posts.map(p=>p.id),['3','2']);assert.equal(b.checkpoint?.pending,null);assert.equal(b.scope?.mode,'latest');
 assert.equal(b.upstream_at,null);assert.ok(!JSON.stringify(b.raw).includes('"id":"1"'));
});
test('quiet recent window is healthy; empty or invalid provider timeline is not',async()=>{
 const quiet=await collectLatestTimeline(24,(async()=>page([row('1',now-90000)])) as typeof fetch);
 assert.equal(quiet.posts.length,0);assert.equal(quiet.coverage,'complete');
 await assert.rejects(collectLatestTimeline(24,(async()=>page([])) as typeof fetch),/empty_target/);
 await assert.rejects(collectLatestTimeline(24,(async()=>new Response(null,{status:403})) as typeof fetch),/http_403/);
 for(const hours of [0,Infinity,169,1.5]) await assert.rejects(collectLatestTimeline(hours,(async()=>{throw new Error('must not fetch');}) as typeof fetch),/lookback/);
});
test('automatic latest interpretation is bounded, idempotent, retryable and does not reprocess archived history',async(t)=>{
 const cwd=process.cwd(),savedCpu=process.env.CPU_READY,savedBudget=process.env.SYNC_BUDGET_MS;
 const root=await mkdtemp(join(tmpdir(),'latest-ai-'));process.chdir(root);delete process.env.CPU_READY;process.env.SYNC_BUDGET_MS='240000';
 t.after(()=>{process.chdir(cwd);if(savedCpu===undefined)delete process.env.CPU_READY;else process.env.CPU_READY=savedCpu;if(savedBudget===undefined)delete process.env.SYNC_BUDGET_MS;else process.env.SYNC_BUDGET_MS=savedBudget;});
 await writeJson('config/source.json',{provider:'fxembed',mode:'latest',lookback_hours:24});
 await writeJson('config/selection.json',{enabled:true,model:'lfm25',max_posts:2,reason:'operator-enabled test'});
 await writeJson('config/models.lock.json',{runtime:{sha256:'r'},models:{lfm25:{sha256:'m'}}});
 const archived=sourceOnly({id:'999',url:'https://x.com/thsottiaux/status/999',text:'Archived original',posted_at:new Date((now-90000)*1000).toISOString(),truncated:false,kind:'post'},'historic');
 await writeJson('data/events.json',{schema_version:1,last_success_at:null,events:[archived]});
 await writeJson('data/state.json',{schema_version:1,processed:{},last_success_at:null,last_attempt_at:null,last_error:null,collection:{provider:'fxembed',checkpoint:{watermark:'bad old watermark',pending:{cursor:'old-backfill'}}}});
 let rows=[row('999',now-90000),row('1',now-180),row('2',now-120),row('3',now-60),{...row('4',now-30),truncated:true}];
 const urls:string[]=[];t.mock.method(globalThis,'fetch',async(u:RequestInfo|URL)=>{urls.push(String(u));return page(rows);});
 assert.equal((await fetchSource({watermark:'bad',pending:null})).posts.length,4);
 await planSync();let calls=0;await applySync(async()=>{calls++;return unknown;});assert.equal(calls,2);
 let report=await readJson<any>('.cache/sync-report.json');assert.equal(report.analysis.succeeded,2);assert.equal(report.pending,1);
 assert.equal((await readJson<any>('data/events.json')).events.find((e:any)=>e.id==='4').temporal.reason,'source_truncated');
 await planSync();assert.deepEqual((await readJson<any>('.cache/pending.json')).pending.map((p:any)=>p.id),['1']);
 await applySync(async()=>{throw new Error('temporary_inference_failure');});
 assert.equal((await readJson<any>('.cache/sync-report.json')).analysis.failed,1);
 await planSync();assert.equal((await readJson<any>('.cache/pending.json')).pending.length,1);
 await applySync(async()=>unknown);
 await planSync();assert.equal((await readJson<any>('.cache/pending.json')).pending.length,0);
 await applySync(async()=>{throw new Error('unchanged source must not call AI');});
 assert.ok(urls.every(u=>!u.includes('cursor=')));
 assert.deepEqual((await readJson<any>('data/events.json')).events.find((e:any)=>e.id==='999'),archived);
 rows[2]=row('2',now-120,'Edited product announcement.');
 await planSync();process.env.CPU_READY='skipped';await applySync(async()=>{throw new Error('must not call skipped CPU');});
 const edited=(await readJson<any>('data/events.json')).events.find((e:any)=>e.id==='2');
 assert.equal(edited.temporal.reason,'pending_cpu');assert.equal((await readdir('data/history')).length,1);
 await planSync();assert.equal((await readJson<any>('.cache/pending.json')).pending.length,1);
 const before=await readFile('data/events.json','utf8');rows=[];await assert.rejects(planSync(),/empty_target/);assert.equal(await readFile('data/events.json','utf8'),before);
});
